### PR TITLE
LOG_FILE was undefined ...?

### PR DESCRIPTION
**Pull request by alexAubin**
c.f. https://forum.yunohost.org/t/calibreweb-erreur-lors-de-la-mise-a-jour/11593/3

I don't understand your last two commits from yesterday ... to me it was working fine (though absolutely not tested) and I don't understand the need to remove/move that line to install ....

Anyway the bug was triggered because the var was not defined during upgrade ...

Also I stumbled upon this line : 

```
conf="\"UPDATE settings SET $(. <(echo -E echo $(<../conf/init_calibre_db_settings))), $(. <(echo -E echo $(<../conf/init_calibre_db_ldap_settings))) WHERE ID=1\""
```

Which looks really weird and overcomplicated but I guess there are some reasons behind it x_X

### CODE REVIEW

**Comment by Krakinou** [comment]
Hmm, okayyy... I don't understand them neither...
I guess that's what happen when one tries to merge a local testing with another pull request and don't test it through package_check before pushing to master...
Lesson learned : **always test even if one is pretty confident...**
I've just push a correction to testing and I'm running a package_check test to check if everything is all right : will push to master shortly if no big issues.
As of now, it seems that "multiinstance" and "port already used" failed (which is strange as they were previously correct and nothing changed in those scripts...). I don't have time to check it right now but will do during this week.

Now about the code : 
- `source ./_common.sh` has to be AFTER retrieving manifest informations as the log file depend on the apps name and instance. I was wondering if it was better to redefined it every time in each script or change the standard orders of the instruction and finally decided for the later.
- weird and overcomplicated line (I agree) is used to create a sqlite3 command to update database settings directly in calibreweb database. It allows me to have config files (namely `init_calibre_db_settings` & `init_calibre_db_ldap_settings`) where I just have to add the columns I need to update. As the settings have evolved over the course of different upstream versions, it was for more convenient this way than to have new line of codes for each settings. If you have a simpler way, I'm ready to change it!

**Comment by alexAubin** [comment]
Hmyup I understand

About the complicated line : I was more concerned about the fact that there's something like 3 or 4 layers of strange redirections (like `<(...)` and `echo -E echo`) that looks reeaaaaally complex for what you're trying to achieve (and I realize there's even an `eval` later)

In fact the need to have `source _common.sh` after defining var is also an indication that something could be improved (considering this LOG_FILE var is in fact only used to build the sql query ? (+ the fact that all the logic elements of this query are spread over 4~5 files)

It looks like you should just have a function in _common.sh that you can call to generate the content of your `$conf` variable (e.g. `$conf=$(build_sql_query)` or whatever you like) then have something like (rough untested draft) : 

```bash
function build_sql_query()
{
    local log_file=/var/log/$app/$app.log
    local access_log_file=...

    cp ./conf/init_calibre_db_settings /tmp/init_calibre_db_settings
    ynh_replace_string "__LOG_FILE__" "$log_file" /tmp/init_calibre_db_settings
    ynh_replace_string "__ACCESS_LOG_FILE__" "$log_file" /tmp/init_calibre_db_settings
    # and other things you need to replace...? Well that's stating to look tedious... but if we had a real template engine that would be just one line of code... 

    echo "UPDATE settings SET $(cat /tmp/init_calibre_db_settings) WHERE ID=1"
}
```

but then it's pretty easy for me to randomly jump in and criticize existing code without understanding all the tiny details and design constrains :sweat_smile: That's really just to try to improve clarity because I was internally screaming when stumbling on this line :sweat_smile:

**Comment by Krakinou** [comment]
Yep, sure the syntax is a little bit cumbersome, but it was one of my first script and I didn't pay it attention since I got it working (the eval/echo/echo -E stuff is due to special characters and variable expansion, honestly I don't recall anymore why did I do this like that, but it seemed logical at the time).
In previous version, log file was not set in the database but in the service, that's why it seems so complicated now as these are not required anymore (and thanks to you to point it out!)

I agree with you that a function would be easier to read, but if I put function in _common.sh, package_linter throws warnings all over the place that I shouldn't put functions in it and set them directly in scripts...

Anyway, I rather your proposal and will work on it for a next release.

**Comment by alexAubin** [comment]
Sounds like it got fixed since then, therefore closing :stuck_out_tongue_winking_eye:

**Pull request closed without merging**
