### PR TITLE
Upgrade to 0.6.14

### PR DESCRIPTION
**Pull request by Thovi98**
## Problem

- New version of the app

## Solution

- Upgrade to 0.6.14

## PR Status

- [x] Code finished and ready to be reviewed/tested
- [ ] The fix/enhancement were manually tested (if applicable)

## Automatic tests

Automatic tests can be triggered on https://ci-apps-dev.yunohost.org/ *after creating the PR*, by commenting "!testme", "!gogogadgetoci" or "By the power of systemd, I invoke The Great App CI to test this Pull Request!". (N.B. : for this to work you need to be a member of the Yunohost-Apps organization)

### CODE REVIEW

**Comment by Krakinou** [comment]
!testme

**Comment by Krakinou** [comment]
Hi
Thanks a lot for the PR.
There are still a few errors in the patch application: namely admin.html and optional-requirements.txt.
You can see them in the [package_check logs](https://ci-apps-dev.yunohost.org/ci/logs/calibreweb_amd64_stable_complete.log) from line 12271.

**Comment by Thovi98** [comment]
Ouch, thank you for pointing me this out. My skills are not that great yet, I don’t know what I have to change 😇

**Comment by Thovi98** [comment]
I’ve just tried updating the app-optional-requirements.txt.patch but I don’t know if I did it the right way... There was different colors I didn’t understand... 😇 
I didn’t find how to update the admin.html file.

**Comment by Krakinou** [comment]
You have to use the `diff` util from command line to generate the patch files (maybe they are other ones with a GUI, don't know).
This util will compare 2 files and generate a patch file that describe the difference between them.
The yunohost helper will then use this patch file to change source files from the upstream.
When I do it, I download the upstream sources, then copy and change the files as I and them to be, and finally generate the patch files.

Usually, the files do not change to much from version to version, but sometimes they do :)

**Comment by Thovi98** [comment]
Waow thanks for the explanation @Krakinou !! 🤩
I will not be able to try this before some weeks I think, so don't hesitate to take the lead of this PR. I will try in a future version when I have more time and an easier access to a computer.

**Pull request merged**
