### PR TITLE
Apply last example_ynh

### PR DESCRIPTION
**Pull request by yalh76**
## Problem
- *Not ready for buster*

## Solution
- *Apply example_ynh*

## PR Status
- [ ] Code finished.
- [ ] Tested with Package_check.
- [ ] Fix or enhancement tested.
- [ ] Upgrade from last version tested.
- [ ] Can be reviewed and tested.

## Package_check results
---
[Build Status/badge/icon)](https://ci-apps-dev.yunohost.org/jenkins/job/calibreweb_ynh%20PR47%20(yalh76)/)

### CODE REVIEW

**Comment by Krakinou** [comment]
Hello there!
Ok... Thanks... I guess...
What should I do with this PR? Should I work on it or are you still pushing fix? 
I'm more use to work alone on this app so I'm not really sure what is expected from me?
Should I set a VM on buster to test the new packages? Or test it on Stretch with the new template applied (side note : one day, I will have a few questions about this template... like should the function be in common.sh or not?)

**Comment by yalh76** [comment]
For now, I have to make it works, I will ask for you review and let you merge when ready :)
I'm doing package_check on buster and stretch. I will put the results before make this PR ready to review

usually, it's better to have functions in _common.sh, but when using experimental helpers, I prefer to have each helper in its own file because it's easier to update them.

**Comment by yalh76** [comment]
I think I made too much changes, calibreweb doesn't start listening on port 8083

**Comment by Krakinou** [comment]
Will give it a look when I'm back from holidays


-------- Message d'origine --------
De : yalh76 <notifications@github.com>
Date : 06/08/2020 20:14 (GMT+01:00)
À : YunoHost-Apps/calibreweb_ynh <calibreweb_ynh@noreply.github.com>
Cc : Krakinou <misterl56@hotmail.com>, Comment <comment@noreply.github.com>
Objet : Re: [YunoHost-Apps/calibreweb_ynh] Apply last example_ynh (#47)


I think I made too much changes, calibreweb doesn't start listening on port 8083

**Pull request closed without merging**
